interaction with the chessboard
TouchTheGrass/tpc-core pull request #17
Opened 2023-01-03 23:33 UTC by EVolkova99

Closes #8

2023-01-04 09:55 UTC, Reversean requested changes
В целом по mr:

- все файлы нужно перенести в `tpc-core/app/services/chess_classes`
- в файле `tpc-core/app/services/engine.py` нужно заменить заглушки на полноценные реализации функции:
  - `get_pieces`
  - `get_possible_moves`
  - `move_piece`

2023-01-04 09:55 UTC, Reversean commented on chess_classes/Board.py
> +                self.board[Position.get(c, 3, i)] = None
Изменения явно относятся к #5

Просьба разделить изменения на несколько mr-ов в зависимости от определенной задачи, иначе сложно ревьювить

2023-01-04 09:55 UTC, Reversean commented on chess_classes/PieceType.py
> +class PieceType(Enum):
Лучше использовать уже существующий класс  `PieceType`

2023-01-04 09:55 UTC, Reversean commented on chess_classes/Position.py
> +    def getColour(self):
Орфографическая ошибка

2023-01-04 09:55 UTC, Reversean commented on chess_classes/Board.py
> +    # функция переставления фигуры с помощью введения начальной и конечной координаты строкового формата 'A8'
Лучше поддерживать один формат документирования функций (docstrings кажется более предпочтительным вариантом, однострочные комментарии можно оставить внутри функции)

2023-01-04 09:55 UTC, Reversean commented on chess_classes/Board.py
> +    def getPiece(self, position):
Давай придерживаться единого [code style для python](https://peps.python.org/pep-0008/#naming-conventions) и именовать функции в нижнем кейсе с андерлайнами в качестве разделителей

2023-01-04 21:19 UTC, EVolkova99 commented on chess_classes/Board.py
> +    def all_positions_of_colour(self, colour):
А почему ошибка? Цитата из интернета - "Современный английский допускает два варианта написания этого слова: colour и color. Произносятся они совершенно одинаково. В Великобритании мы чаще встретим colour, а color — это американский вариант."

2023-01-04 21:55 UTC, EVolkova99 commented on chess_classes/PieceType.py
> +    def getChar(self):
Это уже не нужно, забыла убрать

2023-01-04 21:57 UTC, EVolkova99 commented on chess_classes/Position.py
> +    def getColour(self):
Если ты про Colour, то, как писала выше, допускается писать как color, так и colour

2023-01-04 23:30 UTC, EVolkova99 commented on chess_classes/Colour.py
> +class Colour(Enum):
Где можно найти его реализацию?

2023-01-05 13:13 UTC, Reversean commented on chess_classes/Board.py
> +    def all_positions_of_colour(self, colour):
![image](https://user-images.githubusercontent.com/43142829/210788101-eba4c154-f783-4ea9-a18c-da859d8f1172.png)

2023-01-05 13:15 UTC, Reversean commented on chess_classes/Colour.py
> +class Colour(Enum):
`tpc-core/app/models/enumerations/piece_color.py`

2023-01-05 20:20 UTC, EVolkova99 commented on chess_classes/PieceType.py
> +class PieceType(Enum):
Сделано. Добавила методы из своей реализации для установки правил ходов фигур.

2023-01-05 20:33 UTC, EVolkova99 commented on chess_classes/Piece.py
> +class Piece:
По моему, у этих классов отличаются задачи. Через класс Piece создаются объекты только для того, чтобы их записать в словарь, по которому будет оцениваться возможность сделать ход. Там не требуется информация об игровой сессии, а изменений вроде как много придется делать в таком случае.

2023-01-05 20:33 UTC, EVolkova99 commented on chess_classes/Colour.py
> +class Colour(Enum):
Сделано

2023-01-05 20:44 UTC, EVolkova99 commented on chess_classes/Board.py
> +                self.board[Position.get(c, 3, i)] = None
А я изменения после ревью только сейчас залила. Ты про конструктор класса Board, я так понимаю. Ты имеешь в виду слинковать ишью #5 и отдельный фрагмент кода с этим конструктором?

2023-01-05 20:44 UTC, EVolkova99 commented on chess_classes/Board.py
> +    """
Сделано

2023-01-07 17:26 UTC, Reversean commented on app/services/engine.py
> +            PieceModel.objects.get(id=piece_id).position=position
Это можно вынести вне `if`

2023-01-07 17:31 UTC, Reversean approved these changes

2023-01-07 17:32 UTC, merged